services:
  - type: web
    name: safe-project
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_GCServer
        value: "0"
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_GCHeapHardLimit
        value: "268435456"
